class AetherConfig:
    INTENT_THRESHOLD = 0.45
    PATTERN_THRESHOLD = 0.55
    SYLLABUS_THRESHOLD = 0.50
    RETRIEVAL_THRESHOLD = 0.40
    GLOBAL_MIN_CONFIDENCE = 0.50
    TOP_K_CANDIDATES = 3
    INTENT_WEIGHT = 0.4
    PATTERN_WEIGHT = 0.6

config_store = AetherConfig()