from pptx import Presentation
import os

def generate_ppt_file(history):
    prs = Presentation()
    
    title_slide = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide)
    slide.shapes.title.text = "Aether Lecture Summary"
    slide.placeholders[1].text = "Generated by Aether AI Teaching System"

    for entry in history:
        bullet_slide = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide)
        slide.shapes.title.text = entry["intent"].upper()
        slide.placeholders[1].text = entry["text"]

    output_path = "lecture_summary.pptx"
    prs.save(output_path)
    return output_path
